### PR TITLE
Fixed #17

### LINKED ISSUE #17: Incompatible with RN 0.63.4? (Task :iconscout_react-native-unicons:compileDebugJavaWithJavac FAILED)
Running `react-native run-android` on my project using `react-native 0.63.4` fails with the following:

```
/Users/unicons-issue/failing-project/node_modules/@iconscout/react-native-unicons/android/src/main/java/com/reactlibrary/UniconsPackage.java:13: error: UniconsPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class UniconsPackage implements ReactPackage {
       ^
1 error
3 warnings

FAILURE: Build failed with an exception.
```

### PR DESCRIPTION
**Pull request by joeyfigaro**
Takes care of `Task :iconscout_react-native-unicons:compileDebugJavaWithJavac FAILED` during build on react-native ^0.63.4 from #17

### CODE REVIEW

**Comment by joeyfigaro** [comment]
@tarunmangukiya @rankarpan any thoughts here?

**Comment by joeyfigaro** [comment]
💀
